/**
 * Antigravity Autonomous Engine — Analyst Agent
 *
 * Responsibilities:
 *  - Analyse repository metrics (PR velocity, issue age, code churn)
 *  - Analyse GitHub Actions usage (run frequency, failure rate)
 *  - Write an analysis report to tasks/specs/analysis-report-{date}.md
 *  - Surface high-priority actionable items in todo.md
 *  - Send a digest to Slack if SLACK_WEBHOOK_URL is set
 */

import {
  buildContext,
  sendSlackMessage,
  log,
  logResult,
  type AgentContext,
  type AgentResult,
} from "./_shared.js";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface PRStats {
  open: number;
  mergedLast7Days: number;
  avgAgeHours: number;
}

function getPRStats(): PRStats {
  try {
    const openRaw = execSync(
      "gh pr list --state open --json createdAt --limit 100",
      { encoding: "utf8" }
    );
    const openPRs = JSON.parse(openRaw) as Array<{ createdAt: string }>;

    const mergedRaw = execSync(
      "gh pr list --state merged --limit 50 --json mergedAt",
      { encoding: "utf8" }
    );
    const mergedPRs = JSON.parse(mergedRaw) as Array<{ mergedAt: string | null }>;
    const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recentMerged = mergedPRs.filter(
      (pr) => pr.mergedAt && new Date(pr.mergedAt).getTime() > sevenDaysAgo
    );

    const now = Date.now();
    const ages = openPRs.map(
      (pr) => (now - new Date(pr.createdAt).getTime()) / 3_600_000
    );
    const avgAgeHours =
      ages.length > 0 ? ages.reduce((a, b) => a + b, 0) / ages.length : 0;

    return {
      open: openPRs.length,
      mergedLast7Days: recentMerged.length,
      avgAgeHours: Math.round(avgAgeHours),
    };
  } catch {
    return { open: 0, mergedLast7Days: 0, avgAgeHours: 0 };
  }
}

interface RunStats {
  totalLast7Days: number;
  failures: number;
  failureRate: string;
}

function getRunStats(): RunStats {
  try {
    const raw = execSync(
      "gh run list --limit 100 --json conclusion,createdAt",
      { encoding: "utf8" }
    );
    const runs = JSON.parse(raw) as Array<{ conclusion: string; createdAt: string }>;
    const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = runs.filter(
      (r) => new Date(r.createdAt).getTime() > sevenDaysAgo
    );
    const failures = recent.filter((r) => r.conclusion === "failure").length;
    const failureRate =
      recent.length > 0
        ? `${Math.round((failures / recent.length) * 100)}%`
        : "N/A";
    return { totalLast7Days: recent.length, failures, failureRate };
  } catch {
    return { totalLast7Days: 0, failures: 0, failureRate: "N/A" };
  }
}

// ---------------------------------------------------------------------------
// Core logic
// ---------------------------------------------------------------------------

async function runAnalyst(ctx: AgentContext): Promise<AgentResult> {
  const result: AgentResult = {
    success: false,
    summary: "",
    artifacts: [],
    errors: [],
  };

  log(ctx, "info", "Analyst agent starting");

  const prStats = getPRStats();
  const runStats = getRunStats();
  const date = new Date().toISOString().split("T")[0];

  const report = [
    `# Analysis Report — ${date}`,
    "",
    `**Generated by:** Analyst Agent  `,
    `**Run ID:** ${ctx.runId}`,
    "",
    "## Pull Request Metrics",
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Open PRs | ${prStats.open} |`,
    `| Merged (last 7 days) | ${prStats.mergedLast7Days} |`,
    `| Avg PR age | ${prStats.avgAgeHours}h |`,
    "",
    "## CI / GitHub Actions",
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Runs (last 7 days) | ${runStats.totalLast7Days} |`,
    `| Failures | ${runStats.failures} |`,
    `| Failure rate | ${runStats.failureRate} |`,
    "",
    "## Recommendations",
    "",
    prStats.open > 10
      ? "- ⚠️  More than 10 open PRs — consider scheduling a review sprint"
      : "- ✅  PR backlog is healthy",
    runStats.failures > 3
      ? "- ⚠️  High CI failure rate — Debugger agent should investigate"
      : "- ✅  CI failure rate is acceptable",
    "",
    "## Action Items",
    "",
    "- [ ] Review stale PRs older than 48h",
    runStats.failures > 3 ? "- [ ] Run Debugger agent to investigate CI failures" : "",
  ]
    .filter((l) => Boolean(l))
    .join("\n");

  const reportPath = path.join(
    ctx.repoRoot,
    "tasks",
    "specs",
    `analysis-report-${date}.md`
  );

  if (!ctx.dryRun) {
    fs.writeFileSync(reportPath, report, "utf8");
    log(ctx, "info", `Report written to ${reportPath}`);
  } else {
    log(ctx, "info", `[DRY RUN] Would write report to ${reportPath}`);
  }

  result.artifacts.push(reportPath);

  // Slack digest
  const slackWebhook = process.env.SLACK_WEBHOOK_URL ?? "";
  const digest = `📊 *Analyst Report — ${date}*\nOpen PRs: ${prStats.open} | Merged (7d): ${prStats.mergedLast7Days}\nCI runs (7d): ${runStats.totalLast7Days} | Failures: ${runStats.failures} (${runStats.failureRate})`;
  sendSlackMessage(slackWebhook, digest);

  result.success = true;
  result.summary = `Analyst generated report for ${date}`;
  return result;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

(async () => {
  const ctx = buildContext("Analyst");
  try {
    const result = await runAnalyst(ctx);
    logResult(ctx, result);
    process.exit(result.success ? 0 : 1);
  } catch (err) {
    console.error("[Analyst] Fatal error:", err);
    process.exit(1);
  }
})();
