/**
 * Antigravity Autonomous Engine — Morning Briefing Agent
 *
 * Responsibilities:
 *  - Collect a snapshot of repository health (open PRs, CI status, open issues)
 *  - Load analysis and security reports from tasks/specs/
 *  - Compose a human-readable morning digest
 *  - Post the digest to Slack (SLACK_WEBHOOK_URL) and/or create a GitHub Discussion/Issue
 *  - Append a summary to notes/lessons.md for the self-improvement loop
 */

import {
  buildContext,
  appendLesson,
  sendSlackMessage,
  log,
  logResult,
  type AgentContext,
  type AgentResult,
} from "./_shared.js";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Data gathering
// ---------------------------------------------------------------------------

interface RepoBriefing {
  date: string;
  openPRs: number;
  openIssues: number;
  recentFailures: number;
  latestAnalysisReport: string | null;
  latestSecurityReport: string | null;
  openTasks: number;
}

function gatherBriefing(ctx: AgentContext): RepoBriefing {
  const date = new Date().toISOString().split("T")[0];
  let openPRs = 0;
  let openIssues = 0;
  let recentFailures = 0;

  try {
    const prRaw = execSync(
      "gh pr list --state open --json number --limit 100",
      { encoding: "utf8" }
    );
    openPRs = (JSON.parse(prRaw) as unknown[]).length;
  } catch {
    openPRs = 0;
  }

  try {
    const issueRaw = execSync(
      "gh issue list --state open --json number --limit 100",
      { encoding: "utf8" }
    );
    openIssues = (JSON.parse(issueRaw) as unknown[]).length;
  } catch {
    openIssues = 0;
  }

  try {
    const runRaw = execSync(
      "gh run list --status failure --limit 10 --json conclusion",
      { encoding: "utf8" }
    );
    recentFailures = (JSON.parse(runRaw) as unknown[]).length;
  } catch {
    recentFailures = 0;
  }

  // Find latest reports
  const specsDir = path.join(ctx.repoRoot, "tasks", "specs");
  let latestAnalysisReport: string | null = null;
  let latestSecurityReport: string | null = null;

  if (fs.existsSync(specsDir)) {
    const files = fs.readdirSync(specsDir);
    const analysisFiles = files
      .filter((f) => f.startsWith("analysis-report-"))
      .sort()
      .reverse();
    const securityFiles = files
      .filter((f) => f.startsWith("security-report-"))
      .sort()
      .reverse();

    if (analysisFiles.length > 0) {
      const p = path.join(specsDir, analysisFiles[0]);
      latestAnalysisReport = fs.readFileSync(p, "utf8");
    }
    if (securityFiles.length > 0) {
      const p = path.join(specsDir, securityFiles[0]);
      latestSecurityReport = fs.readFileSync(p, "utf8");
    }
  }

  // Count open tasks
  const todoPath = path.join(ctx.repoRoot, "todo.md");
  let openTasks = 0;
  if (fs.existsSync(todoPath)) {
    const todo = fs.readFileSync(todoPath, "utf8");
    openTasks = (todo.match(/^- \[ \]/gm) ?? []).length;
  }

  return {
    date,
    openPRs,
    openIssues,
    recentFailures,
    latestAnalysisReport,
    latestSecurityReport,
    openTasks,
  };
}

// ---------------------------------------------------------------------------
// Briefing composition
// ---------------------------------------------------------------------------

function composeBriefing(data: RepoBriefing, runId: string): string {
  const statusEmoji = data.recentFailures > 0 ? "⚠️" : "✅";

  const lines = [
    `# 🌅 Morning Briefing — ${data.date}`,
    "",
    `**Generated by:** Morning Briefing Agent  `,
    `**Run ID:** ${runId}`,
    "",
    "## Repository Health",
    "",
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Open PRs | ${data.openPRs} |`,
    `| Open Issues | ${data.openIssues} |`,
    `| Recent CI Failures | ${data.recentFailures} ${statusEmoji} |`,
    `| Open Todo Tasks | ${data.openTasks} |`,
    "",
  ];

  if (data.latestAnalysisReport) {
    lines.push(
      "## Latest Analysis",
      "",
      data.latestAnalysisReport.split("\n").slice(0, 20).join("\n"),
      "",
      "_(see tasks/specs/ for full report)_",
      ""
    );
  }

  if (data.latestSecurityReport) {
    lines.push(
      "## Latest Security",
      "",
      data.latestSecurityReport.split("\n").slice(0, 15).join("\n"),
      "",
      "_(see tasks/specs/ for full report)_",
      ""
    );
  }

  lines.push(
    "## Today's Priorities",
    "",
    data.recentFailures > 0
      ? "1. 🚨 Investigate recent CI failures (run Debugger agent)"
      : "1. ✅ CI is green — continue normal development",
    data.openPRs > 5
      ? "2. ⏳ Review open PRs — backlog growing"
      : "2. ✅ PR backlog is healthy",
    data.openTasks > 0
      ? `3. 📋 ${data.openTasks} task(s) pending in todo.md`
      : "3. ✅ No pending tasks",
    ""
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Core logic
// ---------------------------------------------------------------------------

async function runMorningBriefing(ctx: AgentContext): Promise<AgentResult> {
  const result: AgentResult = {
    success: false,
    summary: "",
    artifacts: [],
    errors: [],
  };

  log(ctx, "info", "Morning Briefing agent starting");

  const data = gatherBriefing(ctx);
  const briefing = composeBriefing(data, ctx.runId);

  // Write briefing to tasks/specs/
  const briefingPath = path.join(
    ctx.repoRoot,
    "tasks",
    "specs",
    `briefing-${data.date}.md`
  );

  if (!ctx.dryRun) {
    fs.writeFileSync(briefingPath, briefing, "utf8");
    log(ctx, "info", `Briefing written to ${briefingPath}`);
  } else {
    log(ctx, "info", `[DRY RUN] Would write briefing to ${briefingPath}`);
    log(ctx, "info", briefing);
  }

  result.artifacts.push(briefingPath);

  // Post to Slack
  const slackWebhook = process.env.SLACK_WEBHOOK_URL ?? "";
  const slackText = [
    `🌅 *Morning Briefing — ${data.date}*`,
    `Open PRs: ${data.openPRs} | Open Issues: ${data.openIssues} | CI Failures: ${data.recentFailures} | Todo Tasks: ${data.openTasks}`,
    data.recentFailures > 0
      ? "⚠️ CI failures detected — check the Debugger agent run."
      : "✅ Repository is healthy.",
  ].join("\n");

  sendSlackMessage(slackWebhook, slackText);

  // Append to lessons
  appendLesson(
    {
      date: data.date,
      agent: "MorningBriefing",
      context: "Daily health snapshot",
      lesson: `PRs: ${data.openPRs}, Issues: ${data.openIssues}, CI failures: ${data.recentFailures}, Todo: ${data.openTasks}`,
    },
    ctx.repoRoot
  );

  result.success = true;
  result.summary = `Morning Briefing generated for ${data.date}`;
  return result;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

(async () => {
  const ctx = buildContext("MorningBriefing");
  try {
    const result = await runMorningBriefing(ctx);
    logResult(ctx, result);
    process.exit(result.success ? 0 : 1);
  } catch (err) {
    console.error("[MorningBriefing] Fatal error:", err);
    process.exit(1);
  }
})();
