/**
 * Antigravity Autonomous Engine — Security Agent
 *
 * Responsibilities:
 *  - Scan dependencies for known vulnerabilities (npm audit)
 *  - Scan diffs for accidental secret leakage
 *  - Run static analysis checks
 *  - Open a security advisory PR if issues are found
 *  - Never commit or expose secrets; abort if a secret pattern is detected
 */

import {
  buildContext,
  appendLesson,
  createBranch,
  commitAll,
  pushBranch,
  openPR,
  log,
  logResult,
  type AgentContext,
  type AgentResult,
} from "./_shared.js";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

// ---------------------------------------------------------------------------
// Secret patterns (must match .agent-safety.yml)
// ---------------------------------------------------------------------------

const SECRET_PATTERNS = [
  /(?:api_key|secret|password|token|private_key)\s*=\s*['"][^'"]{8,}/i,
  /sk-[a-zA-Z0-9]{20,}/,
  /ghp_[a-zA-Z0-9]{36}/,
  /-----BEGIN.*PRIVATE KEY-----/,
];

function detectSecrets(diff: string): string[] {
  const findings: string[] = [];
  for (const pattern of SECRET_PATTERNS) {
    const match = diff.match(pattern);
    if (match) {
      findings.push(
        `Possible secret detected matching pattern: ${pattern.source}`
      );
    }
  }
  return findings;
}

// ---------------------------------------------------------------------------
// npm audit
// ---------------------------------------------------------------------------

interface AuditResult {
  passed: boolean;
  critical: number;
  high: number;
  output: string;
}

function runNpmAudit(repoRoot: string): AuditResult {
  try {
    const output = execSync("npm audit --json 2>&1", {
      cwd: repoRoot,
      encoding: "utf8",
    });
    const parsed = JSON.parse(output) as {
      metadata?: { vulnerabilities?: { critical?: number; high?: number } };
    };
    const critical = parsed?.metadata?.vulnerabilities?.critical ?? 0;
    const high = parsed?.metadata?.vulnerabilities?.high ?? 0;
    return { passed: critical === 0 && high === 0, critical, high, output };
  } catch (err) {
    // npm audit exits non-zero when there are vulnerabilities
    const output = err instanceof Error ? err.message : String(err);
    // Try to extract counts from the output
    const critMatch = output.match(/(\d+) critical/);
    const highMatch = output.match(/(\d+) high/);
    const critical = critMatch ? parseInt(critMatch[1], 10) : 0;
    const high = highMatch ? parseInt(highMatch[1], 10) : 0;
    return { passed: critical === 0 && high === 0, critical, high, output };
  }
}

// ---------------------------------------------------------------------------
// Core logic
// ---------------------------------------------------------------------------

async function runSecurity(ctx: AgentContext): Promise<AgentResult> {
  const result: AgentResult = {
    success: false,
    summary: "",
    artifacts: [],
    errors: [],
  };

  log(ctx, "info", "Security agent starting");

  // 1. Scan current diff for secrets
  let diff = "";
  try {
    diff = execSync("git diff HEAD~1 2>/dev/null || git diff --cached", {
      cwd: ctx.repoRoot,
      encoding: "utf8",
    });
  } catch {
    // No previous commit; skip diff scan
  }

  const secretFindings = detectSecrets(diff);
  if (secretFindings.length > 0) {
    const msg = `SECRET DETECTED in diff:\n${secretFindings.join("\n")}`;
    log(ctx, "error", msg);
    result.errors.push(msg);
    appendLesson(
      {
        date: new Date().toISOString().split("T")[0],
        agent: "Security",
        context: "Diff secret scan",
        lesson: msg,
      },
      ctx.repoRoot
    );
    // Abort immediately — never open a PR with a secret in it
    result.summary = "ABORTED: secret pattern detected in diff";
    return result;
  }

  log(ctx, "info", "Diff secret scan passed");

  // 2. npm audit
  const audit = runNpmAudit(ctx.repoRoot);
  log(
    ctx,
    audit.passed ? "info" : "warn",
    `npm audit: critical=${audit.critical} high=${audit.high}`
  );

  const date = new Date().toISOString().split("T")[0];
  const reportPath = path.join(
    ctx.repoRoot,
    "tasks",
    "specs",
    `security-report-${date}.md`
  );

  const report = [
    `# Security Report — ${date}`,
    "",
    `**Generated by:** Security Agent  `,
    `**Run ID:** ${ctx.runId}`,
    "",
    "## Dependency Audit",
    "",
    `| Severity | Count |`,
    `|----------|-------|`,
    `| Critical | ${audit.critical} |`,
    `| High | ${audit.high} |`,
    "",
    audit.passed
      ? "✅ No critical or high vulnerabilities found."
      : "⚠️ Vulnerabilities detected — see recommendations below.",
    "",
    "## Recommendations",
    "",
    audit.critical > 0 ? "- 🚨 Run `npm audit fix` to remediate critical issues immediately." : "",
    audit.high > 0 ? "- ⚠️  Review high-severity advisories and update affected packages." : "",
    audit.passed ? "- ✅ Keep dependencies up to date with `npm outdated`." : "",
  ]
    .filter((l) => Boolean(l))
    .join("\n");

  if (!ctx.dryRun) {
    fs.writeFileSync(reportPath, report, "utf8");
  }

  result.artifacts.push(reportPath);

  if (!audit.passed && !ctx.dryRun) {
    // Open a security advisory PR
    try {
      const branchName = `agent/security-advisory-${date}-${Date.now()}`;
      createBranch(branchName);
      commitAll(`agent(security): security advisory ${date}`);
      pushBranch(branchName);
      const prUrl = openPR(
        `agent(security): advisory — ${audit.critical} critical, ${audit.high} high`,
        `## Security Agent Advisory\n\n${report}\n\n**Run ID:** ${ctx.runId}`,
        ["agent:security"]
      );
      if (prUrl) result.prUrl = prUrl;
      log(ctx, "info", `Security advisory PR opened: ${prUrl}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log(ctx, "error", `Failed to open security advisory PR: ${msg}`);
      result.errors.push(msg);
    }

    appendLesson(
      {
        date,
        agent: "Security",
        context: "npm audit",
        lesson: `Found ${audit.critical} critical and ${audit.high} high vulnerabilities. Run \`npm audit fix\` to remediate.`,
      },
      ctx.repoRoot
    );
  }

  result.success = secretFindings.length === 0;
  result.summary = `Security scan complete. Secrets: ${secretFindings.length}, Critical vulns: ${audit.critical}, High vulns: ${audit.high}`;
  return result;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

(async () => {
  const ctx = buildContext("Security");
  try {
    const result = await runSecurity(ctx);
    logResult(ctx, result);
    process.exit(result.success ? 0 : 1);
  } catch (err) {
    console.error("[Security] Fatal error:", err);
    process.exit(1);
  }
})();
